spring:
  application:
    ####注册中心应用名称
    name:   appconfig
  rabbitmq:
        host: 192.168.81.130
        password: admin
        port: 5672
        username: admin
        virtual-host: /xuexionghui
  cloud:
    config:
    ####读取后缀
      profile: dev
      ####读取config-server注册地址
      discovery:
        service-id: config-server
        enabled: true
        
#####    eureka服务注册地址    
eureka:
  client:
    service-url:
           defaultZone: http://localhost:8080/eureka    
server:
  port: 8883
###开启bus刷新
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh

  
