###服务注册到eureka地址
eureka:
  client:
    service-url:
           defaultZone: http://localhost:8080/eureka
spring:
  application:
    ####注册中心应用名称
    name: config-server
  rabbitmq:
        host: 192.168.81.130
        password: admin
        port: 5672
        username: admin
        virtual-host: /xuexionghui
  cloud:
    config:
      server:
        git:
          ###git环境地址
          uri: https://gitee.com/xuexionghui/config.git
          ####搜索目录
          search-paths:
            - config  
      ####读取分支      
      label: master
####端口号      
server:
  port: 8888

